name: Build Joomla Module

on:
  push:
    tags:
      - '*'
    branches:
      - main
    types: [created]
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  build_module:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Joomla Module Packager
        uses: N6REJ/joomla-packager@2025.6.24
        with:
          author: 'N6REJ'
          copyright-holder: 'N6REJ'
          copyright-start-year: '2025'
          github-token: ${{ secrets.GH_PAT }}
          output-dir: dist
          extension-type: module
          extension-name: mod_bearslivesearch
          php-compat: '8.0,8.1,8.2'
          joomla-compat: '5.0'
          zip-filename: mod_bearslivesearch-latest.zip
